apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-k8s
  template:
    metadata:
      labels:
        app: fastapi-k8s
    spec:
      containers:
        - name: fastapi-k8s
          image: luizmario/fastapi-k8s:latest
          ports:
            - containerPort: 8000
